import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>RESTful-API Web Services - Powered by ASP-MATRIX</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://asp-matrix.com">ASP-MATRIX</a>
        </h1>
        <div className={styles.description}>RESTful Web Services with Node.js and Express</div>
        <p className={styles.description}>
          Get started
          <code className={styles.code}><a href="https://lab.asp-matrix.com/api/hello">https://lab.asp-matrix.com/api/hello</a></code>
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://asp-matrix.com"
        >
          Powered by{' '}
          <span className={styles.logo}>
            {/* <Image src="/vercel.svg" alt="ASP Matrix" width={72} height={16} /> */}
            <b>ASP-MATRIX.com</b>
          </span>
        </a>
      </footer>
    </div>
  )
}
